"""
This type stub file was generated by pyright.
"""

import typing

T = typing.TypeVar('T')
class Model(object):
    swagger_types = ...
    attribute_map = ...
    @classmethod
    def from_dict(cls: typing.Type[T], dikt) -> T:
        """Returns the dict as a model"""
        ...
    
    def to_dict(self):
        """Returns the model properties as a dict

        :rtype: dict
        """
        ...
    
    def to_str(self):
        """Returns the string representation of the model

        :rtype: str
        """
        ...
    
    def __repr__(self):
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other):
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        ...
    


