"""
This type stub file was generated by pyright.
"""

from typing import List
from doctrans_py_swagger_server.models.base_model_ import Model

class DtaserviceDocumentRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file_name: str = ..., document: str = ..., service_name: str = ..., options: List[str] = ...):
        """DtaserviceDocumentRequest - a model defined in Swagger

        :param file_name: The file_name of this DtaserviceDocumentRequest.  # noqa: E501
        :type file_name: str
        :param document: The document of this DtaserviceDocumentRequest.  # noqa: E501
        :type document: str
        :param service_name: The service_name of this DtaserviceDocumentRequest.  # noqa: E501
        :type service_name: str
        :param options: The options of this DtaserviceDocumentRequest.  # noqa: E501
        :type options: List[str]
        """
        self.swagger_types = ...
        self.attribute_map = ...
    
    @classmethod
    def from_dict(cls, dikt) -> DtaserviceDocumentRequest:
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dtaserviceDocumentRequest of this DtaserviceDocumentRequest.  # noqa: E501
        :rtype: DtaserviceDocumentRequest
        """
        ...
    
    @property
    def file_name(self) -> str:
        """Gets the file_name of this DtaserviceDocumentRequest.


        :return: The file_name of this DtaserviceDocumentRequest.
        :rtype: str
        """
        ...
    
    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this DtaserviceDocumentRequest.


        :param file_name: The file_name of this DtaserviceDocumentRequest.
        :type file_name: str
        """
        ...
    
    @property
    def document(self) -> str:
        """Gets the document of this DtaserviceDocumentRequest.


        :return: The document of this DtaserviceDocumentRequest.
        :rtype: str
        """
        ...
    
    @document.setter
    def document(self, document: str):
        """Sets the document of this DtaserviceDocumentRequest.


        :param document: The document of this DtaserviceDocumentRequest.
        :type document: str
        """
        ...
    
    @property
    def service_name(self) -> str:
        """Gets the service_name of this DtaserviceDocumentRequest.


        :return: The service_name of this DtaserviceDocumentRequest.
        :rtype: str
        """
        ...
    
    @service_name.setter
    def service_name(self, service_name: str):
        """Sets the service_name of this DtaserviceDocumentRequest.


        :param service_name: The service_name of this DtaserviceDocumentRequest.
        :type service_name: str
        """
        ...
    
    @property
    def options(self) -> List[str]:
        """Gets the options of this DtaserviceDocumentRequest.


        :return: The options of this DtaserviceDocumentRequest.
        :rtype: List[str]
        """
        ...
    
    @options.setter
    def options(self, options: List[str]):
        """Sets the options of this DtaserviceDocumentRequest.


        :param options: The options of this DtaserviceDocumentRequest.
        :type options: List[str]
        """
        ...
    


