"""
This type stub file was generated by pyright.
"""

from typing import List
from doctrans_py_swagger_server.models.base_model_ import Model
from doctrans_py_swagger_server.models.dtaservice_document_request import DtaserviceDocumentRequest

class DtaserviceTransformPipeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pipe: List[DtaserviceDocumentRequest] = ...):
        """DtaserviceTransformPipeRequest - a model defined in Swagger

        :param pipe: The pipe of this DtaserviceTransformPipeRequest.  # noqa: E501
        :type pipe: List[DtaserviceDocumentRequest]
        """
        self.swagger_types = ...
        self.attribute_map = ...
    
    @classmethod
    def from_dict(cls, dikt) -> DtaserviceTransformPipeRequest:
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dtaserviceTransformPipeRequest of this DtaserviceTransformPipeRequest.  # noqa: E501
        :rtype: DtaserviceTransformPipeRequest
        """
        ...
    
    @property
    def pipe(self) -> List[DtaserviceDocumentRequest]:
        """Gets the pipe of this DtaserviceTransformPipeRequest.


        :return: The pipe of this DtaserviceTransformPipeRequest.
        :rtype: List[DtaserviceDocumentRequest]
        """
        ...
    
    @pipe.setter
    def pipe(self, pipe: List[DtaserviceDocumentRequest]):
        """Sets the pipe of this DtaserviceTransformPipeRequest.


        :param pipe: The pipe of this DtaserviceTransformPipeRequest.
        :type pipe: List[DtaserviceDocumentRequest]
        """
        ...
    


