"""
This type stub file was generated by pyright.
"""

from typing import List
from doctrans_py_swagger_server.models.base_model_ import Model

class DtaserviceListServicesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, services: List[str] = ...):
        """DtaserviceListServicesResponse - a model defined in Swagger

        :param services: The services of this DtaserviceListServicesResponse.  # noqa: E501
        :type services: List[str]
        """
        self.swagger_types = ...
        self.attribute_map = ...
    
    @classmethod
    def from_dict(cls, dikt) -> DtaserviceListServicesResponse:
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dtaserviceListServicesResponse of this DtaserviceListServicesResponse.  # noqa: E501
        :rtype: DtaserviceListServicesResponse
        """
        ...
    
    @property
    def services(self) -> List[str]:
        """Gets the services of this DtaserviceListServicesResponse.


        :return: The services of this DtaserviceListServicesResponse.
        :rtype: List[str]
        """
        ...
    
    @services.setter
    def services(self, services: List[str]):
        """Sets the services of this DtaserviceListServicesResponse.


        :param services: The services of this DtaserviceListServicesResponse.
        :type services: List[str]
        """
        ...
    


