"""
This type stub file was generated by pyright.
"""

"""
    flask.__main__
    ~~~~~~~~~~~~~~

    Alias for flask.run for the command line.

    :copyright: 2010 Pallets
    :license: BSD-3-Clause
"""
if __name__ == "__main__":
    ...
