"""
This type stub file was generated by pyright.
"""

from ._compat import implements_to_string

"""
    flask.debughelpers
    ~~~~~~~~~~~~~~~~~~

    Various helpers to make the development experience better.

    :copyright: 2010 Pallets
    :license: BSD-3-Clause
"""
class UnexpectedUnicodeError(AssertionError, UnicodeError):
    """Raised in places where we want some better error reporting for
    unexpected unicode or binary data.
    """
    ...


@implements_to_string
class DebugFilesKeyError(KeyError, AssertionError):
    """Raised from request.files during debugging.  The idea is that it can
    provide a better error message than just a generic KeyError/BadRequest.
    """
    def __init__(self, request, key):
        self.msg = ...
    
    def __str__(self):
        ...
    


class FormDataRoutingRedirect(AssertionError):
    """This exception is raised by Flask in debug mode if it detects a
    redirect caused by the routing system when the request method is not
    GET, HEAD or OPTIONS.  Reasoning: form data will be dropped.
    """
    def __init__(self, request):
        ...
    


def attach_enctype_error_multidict(request):
    """Since Flask 0.8 we're monkeypatching the files object in case a
    request is detected that does not use multipart form data but the files
    object is accessed.
    """
    class newcls(oldcls):
        ...
    
    

def _dump_loader_info(loader):
    ...

def explain_template_loading_attempts(app, template, attempts):
    """This should help developers understand what failed"""
    ...

def explain_ignored_app_run():
    ...

