version = 1

test_patterns = ["test_*.py"]

exclude_patterns = [
    ".git",
    "__pycache__",
    "tmp"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
