[tool.poetry]
name = "doctrans-py"
version = "0.1.0"
description = ""
authors = ["B4rtware <34386047+B4rtware@users.noreply.github.com>"]

[tool.black]
line-length = 88
target-version = ["py38"]
exclude = """
    /typings
|   /tests
"""

[tool.poetry.dependencies]
python = "^3.8"
grpcio = "^1.26.0"
py-eureka-client = "^0.7.4"
dataclasses-json = "^0.3.7"
grpcio-tools = "^1.26.0"
googleapis-common-protos = "^1.6.0"
falcon = "^2.0.0"
waitress = "^1.4.2"
django = "^3.0.2"
djangorestframework = "^3.11.0"
django-cors-headers = "^3.2.1"
psycopg2 = "^2.8.4"
requests = "^2.22.0"
colorama = "^0.4.3"
connexion = {version = "2.6.0", extras = ["swagger-ui"]}
flask = "^1.1.1"
pytest = "^5.4.1"
flask-swagger-ui = "^3.25.0"
swagger-ui-py = "^0.2.1"
Sphinx = "^3.0.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylint = "^2.4.4"
pyenchant = "^3.0.1"
Sphinx = "^3.0.1"
sphinx-rtd-theme = "^0.4.3"
invoke = "^1.4.1"
protobuf = "^3.11.3"
googleapis-common-protos = "^1.51.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
