[tool.poetry]
name = "doctrans-py"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
grpcio = "^1.26.0"
py-eureka-client = "^0.7.4"
dataclasses-json = "^0.3.7"
grpcio-tools = "^1.26.0"
googleapis-common-protos = "^1.6.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
