"""
This type stub file was generated by pyright.
"""

import logging
from .abstract import AbstractApp
from typing import Any, Optional

logger = logging.getLogger('connexion.aiohttp_app')
class AioHttpApp(AbstractApp):
    def __init__(self, import_name, only_one_api: bool = ..., **kwargs):
        ...
    
    def create_app(self):
        ...
    
    def get_root_path(self):
        ...
    
    def set_errors_handlers(self):
        ...
    
    def add_api(self, specification, **kwargs):
        ...
    
    def _get_api(self, specification, kwargs):
        ...
    
    def run(self, port: Optional[Any] = ..., server: Optional[Any] = ..., debug: Optional[Any] = ..., host: Optional[Any] = ..., **options):
        self.server = ...
        self.host = ...
    


