"""
This type stub file was generated by pyright.
"""

import logging
from flask import json
from .abstract import AbstractApp
from typing import Any, Optional

logger = logging.getLogger('connexion.app')
class FlaskApp(AbstractApp):
    def __init__(self, import_name, server=..., **kwargs):
        ...
    
    def create_app(self):
        ...
    
    def get_root_path(self):
        ...
    
    def set_errors_handlers(self):
        ...
    
    @staticmethod
    def common_error_handler(exception):
        """
        :type exception: Exception
        """
        ...
    
    def add_api(self, specification, **kwargs):
        ...
    
    def add_error_handler(self, error_code, function):
        ...
    
    def run(self, port: Optional[Any] = ..., server: Optional[Any] = ..., debug: Optional[Any] = ..., host: Optional[Any] = ..., **options):
        """
        Runs the application on a local development server.
        :param host: the host interface to bind on.
        :type host: str
        :param port: port to listen to
        :type port: int
        :param server: which wsgi server to use
        :type server: str | None
        :param debug: include debugging information
        :type debug: bool
        :param options: options to be forwarded to the underlying server
        """
        self.host = ...
    


class FlaskJSONEncoder(json.JSONEncoder):
    def default(self, o):
        ...
    


