version: "3.7"

services:
  caeser:
    image: b4rtware/morpho-caeser:latest
    build: ./caeser
    ports:
      - "50000:50000"
    networks:
      - eureka
  permutation:
    image: b4rtware/morpho-permutation:latest
    build: ./permutation
    ports:
      - "50001:50000"
    networks:
      - eureka
  vigenere:
    image: b4rtware/morpho-vigenere:latest
    build: ./vigenere
    ports:
      - "50002:50000"
    networks:
      - eureka
  eureka:
    image: b4rtware/morpho-eureka:latest
    networks:
      - eureka

networks:
  eureka: