version: "3.7"

services:
  caeser:
    image: b4rtware/morpho-caeser:latest
    environment:
      REGISTRAR_URL: http://morpho-crypto-eureka:8761/eureka
    build: ./caeser
    ports: 
      - "50001:50000"
    networks:
      eureka:
        aliases:
          - morpho-crypto-caeser

    depends_on:
      - eureka

  permutation:
    image: b4rtware/morpho-permutation:latest
    environment:
      REGISTRAR_URL: http://morpho-crypto-eureka:8761/eureka
    build: ./permutation
    ports: 
      - "50002:50000"
    networks:
      eureka:
        aliases:
          - morpho-crypto-caeser
    depends_on:
      - eureka

  vigenere:
    image: b4rtware/morpho-vigenere:latest
    environment:
      REGISTRAR_URL: http://morpho-crypto-eureka:8761/eureka
    build: ./vigenere
    ports: 
      - "50003:50000"
    networks:
      eureka:
        aliases:
          - morpho-crypto-caeser
    depends_on:
      - eureka

  gateway: 
    image: b4rtware/morpho-gateway:latest
    environment:
      REGISTRAR_URL: https://eureka.python-morpho.org/eureka
    build: ./gateway
    ports: 
      - "50000:50000"
    networks:
      eureka:
        aliases:
          - morpho-crypto-caeser
    depends_on:
      - eureka

  eureka:
    image: b4rtware/morpho-eureka:latest
    ports:
      - "8761:8761"
    networks:
      eureka:
        aliases:
          - morpho-crypto-eureka

networks:
  eureka:
    name: morpho_crypto_eureka
