"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from pathlib import Path
from typing import Any, Callable, Optional, Type, TypeVar, Union
from pydantic.parse import Protocol

__all__ = ('parse_file_as', 'parse_obj_as')
NameFactory = Union[str, Callable[[Type[Any]], str]]
def _generate_parsing_type_name(type_: Any) -> str:
    ...

@lru_cache(maxsize=2048)
def _get_parsing_type(type_: Any, *, type_name: Optional[NameFactory] = ...) -> Any:
    ...

T = TypeVar('T')
def parse_obj_as(type_: Type[T], obj: Any, *, type_name: Optional[NameFactory] = ...) -> T:
    ...

def parse_file_as(type_: Type[T], path: Union[str, Path], *, content_type: str = ..., encoding: str = ..., proto: Protocol = ..., allow_pickle: bool = ..., json_loads: Callable[[str], Any] = ..., type_name: Optional[NameFactory] = ...) -> T:
    ...

