"""
This type stub file was generated by pyright.
"""

import urllib3
import chardet
import warnings
import logging
from .exceptions import ConnectTimeout, ConnectionError, FileModeWarning, HTTPError, ReadTimeout, RequestException, RequestsDependencyWarning, Timeout, TooManyRedirects, URLRequired
from urllib3.exceptions import DependencyWarning
from .__version__ import __author__, __author_email__, __build__, __cake__, __copyright__, __description__, __license__, __title__, __url__, __version__
from . import packages, utils
from .models import PreparedRequest, Request, Response
from .api import delete, get, head, options, patch, post, put, request
from .sessions import Session, session
from .status_codes import codes
from logging import NullHandler

"""
Requests HTTP Library
~~~~~~~~~~~~~~~~~~~~~

Requests is an HTTP library, written in Python, for human beings.
Basic GET usage:

   >>> import requests
   >>> r = requests.get('https://www.python.org')
   >>> r.status_code
   200
   >>> b'Python is a programming language' in r.content
   True

... or POST:

   >>> payload = dict(key1='value1', key2='value2')
   >>> r = requests.post('https://httpbin.org/post', data=payload)
   >>> print(r.text)
   {
     ...
     "form": {
       "key1": "value1",
       "key2": "value2"
     },
     ...
   }

The other HTTP methods are supported - see `requests.api`. Full documentation
is at <https://requests.readthedocs.io>.

:copyright: (c) 2017 by Kenneth Reitz.
:license: Apache 2.0, see LICENSE for more details.
"""
def check_compatibility(urllib3_version, chardet_version):
    ...

def _check_cryptography(cryptography_version):
    ...

