"""
This type stub file was generated by pyright.
"""

import re
from typing import Any, Optional

PATH_PARAMETER = re.compile(r'\{([^}]*)\}')
PATH_PARAMETER_CONVERTERS = { 'integer': 'int','number': 'float','path': 'path' }
def flaskify_endpoint(identifier, randomize: Optional[Any] = ...):
    """
    Converts the provided identifier in a valid flask endpoint name

    :type identifier: str
    :param randomize: If specified, add this many random characters (upper case
        and digits) to the endpoint name, separated by a pipe character.
    :type randomize: int | None
    :rtype: str
    """
    ...

def convert_path_parameter(match, types):
    ...

def flaskify_path(swagger_path, types: Optional[Any] = ...):
    """
    Convert swagger path templates to flask path templates

    :type swagger_path: str
    :type types: dict
    :rtype: str

    >>> flaskify_path('/foo-bar/{my-param}')
    '/foo-bar/<my_param>'

    >>> flaskify_path('/foo/{someint}', {'someint': 'int'})
    '/foo/<int:someint>'
    """
    ...

def is_flask_response(obj):
    """
    Verifies if obj is a default Flask response instance.

    :type obj: object
    :rtype bool

    >>> is_flask_response(redirect('http://example.com/'))
    True
    >>> is_flask_response(flask.Response())
    True
    """
    ...

