"""
This type stub file was generated by pyright.
"""

from connexion.apps.flask_app import FlaskJSONEncoder

class JSONEncoder(FlaskJSONEncoder):
    include_nulls = ...
    def default(self, o):
        ...
    


