"""
This type stub file was generated by pyright.
"""

from .initialise import colorama_text, deinit, init, reinit
from .ansi import Back, Cursor, Fore, Style
from .ansitowin32 import AnsiToWin32

__version__ = '0.4.3'
