"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from doctrans_py_swagger_client.models.trace import Trace

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
