version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2-buster
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: pip install poetry
      - run:
          name: Install Dependencies
          command: poetry install