version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2-buster
      - image: circleci/openjdk:11.0.7-jdk-buster
    steps:
      - run:
          name: test
          command: java -version
          
      - checkout

      - restore_cache:
          keys: 
            - morpho-{{ checksum "poetry.lock" }}

      - run:
          name: Install Poetry
          command: pip install poetry

      - run:
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: morpho-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Run Unit Tests
          command: |
            mkdir test_results
            poetry run python -m pytest --junitxml=test-results/junit.xml tests/unit

      - run:
          name: Run Integration Tests
          command: |
            poetry run python -m pytest --junitxml=test-results/junit-integration.xml -s tests/integration

      - run:
          name: Run Coverage
          command: |
            poetry run python -m pytest --cov=. tests/unit

      - run:
          name: Send to Codecov
          command: poetry run python -m codecov
          when:
            on_success

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - run:
          name: Send to Telegram
          command: poetry run python -m notifier.py