version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2-buster
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest --color=yes
          name: pytest