"""
This type stub file was generated by pyright.
"""

import logging
from connexion.resolver import Resolver

logger = logging.getLogger(__name__)
class MockResolver(Resolver):
    def __init__(self, mock_all):
        self.mock_all = ...
    
    def resolve(self, operation):
        """
        Mock operation resolver

        :type operation: connexion.operations.AbstractOperation
        """
        ...
    
    def mock_operation(self, operation, *args, **kwargs):
        ...
    


