"""
This type stub file was generated by pyright.
"""

from collections import namedtuple
from typing import Any, Optional

PROXY_HEADERS = frozenset("X_FORWARDED_FOR", "X_FORWARDED_HOST", "X_FORWARDED_PROTO", "X_FORWARDED_PORT", "X_FORWARDED_BY", "FORWARDED")
Forwarded = namedtuple("Forwarded", ["by", "for_", "host", "proto"])
class MalformedProxyHeader(Exception):
    def __init__(self, header, reason, value):
        self.header = ...
        self.reason = ...
        self.value = ...
    


def proxy_headers_middleware(app, trusted_proxy: Optional[Any] = ..., trusted_proxy_count=..., trusted_proxy_headers: Optional[Any] = ..., clear_untrusted: bool = ..., log_untrusted: bool = ..., logger=...):
    ...

def parse_proxy_headers(environ, trusted_proxy_count, trusted_proxy_headers, logger=...):
    ...

def strip_brackets(addr):
    ...

def clear_untrusted_headers(environ, untrusted_headers, log_warning: bool = ..., logger=...):
    ...

