"""
This type stub file was generated by pyright.
"""

import logging

logger = logging.getLogger('connexion.decorators.decorator')
class BaseDecorator(object):
    def __call__(self, function):
        """
        :type function: types.FunctionType
        :rtype: types.FunctionType
        """
        ...
    
    def __repr__(self):
        """
        :rtype: str
        """
        ...
    


class RequestResponseDecorator(BaseDecorator):
    """Manages the lifecycle of the request internally in Connexion.
    Filter the ConnexionRequest instance to return the corresponding
    framework specific object.
    """
    def __init__(self, api, mimetype):
        self.api = ...
        self.mimetype = ...
    
    def __call__(self, function):
        """
        :type function: types.FunctionType
        :rtype: types.FunctionType
        """
        ...
    


