"""
This type stub file was generated by pyright.
"""

class UWSGIMetricsCollector(object):
    def __init__(self, path, method):
        self.path = ...
        self.method = ...
        self.key_suffix = ...
        self.prefix = ...
    
    @staticmethod
    def is_available():
        ...
    
    def __call__(self, function):
        """
        :type function: types.FunctionType
        :rtype: types.FunctionType
        """
        ...
    


