"""
This type stub file was generated by pyright.
"""

from .abstract import AbstractOperation
from .openapi import OpenAPIOperation
from .secure import SecureOperation
from .swagger2 import Swagger2Operation

def make_operation(spec, *args, **kwargs):
    ...

