"""
This type stub file was generated by pyright.
"""

import abc
import logging
from connexion.operations.secure import SecureOperation
from ..decorators.response import ResponseValidator
from ..decorators.validation import ParameterValidator, RequestBodyValidator
from typing import Any, Optional

logger = logging.getLogger('connexion.operations.abstract')
DEFAULT_MIMETYPE = 'application/json'
VALIDATOR_MAP = { 'parameter': ParameterValidator,'body': RequestBodyValidator,'response': ResponseValidator }
class AbstractOperation(SecureOperation, metaclass=abc.ABCMeta):
    """
    An API routes requests to an Operation by a (path, method) pair.
    The operation uses a resolver to resolve its handler function.
    We use the provided spec to do a bunch of heavy lifting before
    (and after) we call security_schemes handler.
    The registered handler function ends up looking something like:

        @secure_endpoint
        @validate_inputs
        @deserialize_function_inputs
        @serialize_function_outputs
        @validate_outputs
        def user_provided_handler_function(important, stuff):
            if important:
                serious_business(stuff)
    """
    def __init__(self, api, method, path, operation, resolver, app_security: Optional[Any] = ..., security_schemes: Optional[Any] = ..., validate_responses: bool = ..., strict_validation: bool = ..., randomize_endpoint: Optional[Any] = ..., validator_map: Optional[Any] = ..., pythonic_params: bool = ..., uri_parser_class: Optional[Any] = ..., pass_context_arg_name: Optional[Any] = ...):
        """
        :param api: api that this operation is attached to
        :type api: apis.AbstractAPI
        :param method: HTTP method
        :type method: str
        :param path:
        :type path: str
        :param operation: swagger operation object
        :type operation: dict
        :param resolver: Callable that maps operationID to a function
        :param app_produces: list of content types the application can return by default
        :param app_security: list of security rules the application uses by default
        :type app_security: list
        :param security_schemes: `Security Definitions Object
            <https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-definitions-object>`_
        :type security_schemes: dict
        :param validate_responses: True enables validation. Validation errors generate HTTP 500 responses.
        :type validate_responses: bool
        :param strict_validation: True enables validation on invalid request parameters
        :type strict_validation: bool
        :param randomize_endpoint: number of random characters to append to operation name
        :type randomize_endpoint: integer
        :param validator_map: Custom validators for the types "parameter", "body" and "response".
        :type validator_map: dict
        :param pythonic_params: When True CamelCase parameters are converted to snake_case and an underscore is appended
        to any shadowed built-ins
        :type pythonic_params: bool
        :param uri_parser_class: class to use for uri parseing
        :type uri_parser_class: AbstractURIParser
        :param pass_context_arg_name: If not None will try to inject the request context to the function using this
        name.
        :type pass_context_arg_name: str|None
        """
        ...
    
    @property
    def method(self):
        """
        The HTTP method for this operation (ex. GET, POST)
        """
        ...
    
    @property
    def path(self):
        """
        The path of the operation, relative to the API base path
        """
        ...
    
    @property
    def responses(self):
        """
        Returns the responses for this operation
        """
        ...
    
    @property
    def validator_map(self):
        """
        Validators to use for parameter, body, and response validation
        """
        ...
    
    @property
    def operation_id(self):
        """
        The operation id used to indentify the operation internally to the app
        """
        ...
    
    @property
    def randomize_endpoint(self):
        """
        number of random digits to generate and append to the operation_id.
        """
        ...
    
    @property
    def router_controller(self):
        """
        The router controller to use (python module where handler functions live)
        """
        ...
    
    @property
    def strict_validation(self):
        """
        If True, validate all requests against the spec
        """
        ...
    
    @property
    def pythonic_params(self):
        """
        If True, convert CamelCase into pythonic_variable_names
        """
        ...
    
    @property
    def validate_responses(self):
        """
        If True, check the response against the response schema, and return an
        error if the response does not validate.
        """
        ...
    
    @staticmethod
    def _get_file_arguments(files, arguments, has_kwargs: bool = ...):
        ...
    
    @abc.abstractmethod
    def _get_val_from_param(self, value, query_defn):
        """
        Convert input parameters into the correct type
        """
        ...
    
    def _query_args_helper(self, query_defns, query_arguments, function_arguments, has_kwargs, sanitize):
        ...
    
    @abc.abstractmethod
    def _get_query_arguments(self, query, arguments, has_kwargs, sanitize):
        """
        extract handler function arguments from the query parameters
        """
        ...
    
    @abc.abstractmethod
    def _get_body_argument(self, body, arguments, has_kwargs, sanitize):
        """
        extract handler function arguments from the request body
        """
        ...
    
    def _get_path_arguments(self, path_params, sanitize):
        """
        extract handler function arguments from path parameters
        """
        ...
    
    @abc.abstractproperty
    def parameters(self):
        """
        Returns the parameters for this operation
        """
        ...
    
    @abc.abstractproperty
    def produces(self):
        """
        Content-Types that the operation produces
        """
        ...
    
    @abc.abstractproperty
    def consumes(self):
        """
        Content-Types that the operation consumes
        """
        ...
    
    @abc.abstractproperty
    def body_schema(self):
        """
        The body schema definition for this operation.
        """
        ...
    
    @abc.abstractproperty
    def body_definition(self):
        """
        The body definition for this operation.
        :rtype: dict
        """
        ...
    
    def get_arguments(self, path_params, query_params, body, files, arguments, has_kwargs, sanitize):
        """
        get arguments for handler function
        """
        ...
    
    def response_definition(self, status_code: Optional[Any] = ..., content_type: Optional[Any] = ...):
        """
        response definition for this endpoint
        """
        ...
    
    @abc.abstractmethod
    def response_schema(self, status_code: Optional[Any] = ..., content_type: Optional[Any] = ...):
        """
        response schema for this endpoint
        """
        ...
    
    @abc.abstractmethod
    def example_response(self, status_code: Optional[Any] = ..., content_type: Optional[Any] = ...):
        """
        Returns an example from the spec
        """
        ...
    
    @abc.abstractmethod
    def get_path_parameter_types(self):
        """
        Returns the types for parameters in the path
        """
        ...
    
    @abc.abstractmethod
    def with_definitions(self, schema):
        """
        Returns the given schema, but with the definitions from the spec
        attached. This allows any remaining references to be resolved by a
        validator (for example).
        """
        ...
    
    def get_mimetype(self):
        """
        If the endpoint has no 'produces' then the default is
        'application/json'.

        :rtype str
        """
        ...
    
    @property
    def _uri_parsing_decorator(self):
        """
        Returns a decorator that parses request data and handles things like
        array types, and duplicate parameter definitions.
        """
        ...
    
    @property
    def function(self):
        """
        Operation function with decorators

        :rtype: types.FunctionType
        """
        ...
    
    @property
    def __content_type_decorator(self):
        """
        Get produces decorator.

        If the operation mimetype format is json then the function return value is jsonified

        From Swagger Specification:

        **Produces**

        A list of MIME types the operation can produce. This overrides the produces definition at the Swagger Object.
        An empty value MAY be used to clear the global definition.

        :rtype: types.FunctionType
        """
        ...
    
    @property
    def __validation_decorators(self):
        """
        :rtype: types.FunctionType
        """
        ...
    
    @property
    def __response_validation_decorator(self):
        """
        Get a decorator for validating the generated Response.
        :rtype: types.FunctionType
        """
        ...
    
    def json_loads(self, data):
        """
        A wrapper for calling the API specific JSON loader.

        :param data: The JSON data in textual form.
        :type data: bytes
        """
        ...
    


