"""
This type stub file was generated by pyright.
"""

from . import core
from .core import EmptyRequestHeaders, httprettified, httpretty
from .errors import HTTPrettyError, UnmockedError
from .version import version

__version__ = version
EmptyRequestHeaders = core.EmptyRequestHeaders
Entry = core.Entry
HTTPrettyRequestEmpty = core.HTTPrettyRequestEmpty
URIInfo = core.URIInfo
URIMatcher = core.URIMatcher
httprettified = core.httprettified
httprettized = core.httprettized
httpretty = core.httpretty
HTTPretty = httpretty
activate = httprettified
enabled = httprettized
enable = httpretty.enable
register_uri = httpretty.register_uri
disable = httpretty.disable
is_enabled = httpretty.is_enabled
reset = httpretty.reset
Response = httpretty.Response
GET = httpretty.GET
PUT = httpretty.PUT
POST = httpretty.POST
DELETE = httpretty.DELETE
HEAD = httpretty.HEAD
PATCH = httpretty.PATCH
OPTIONS = httpretty.OPTIONS
CONNECT = httpretty.CONNECT
def last_request():
    """
    :returns: the last :py:class:`~httpretty.core.HTTPrettyRequest`
    """
    ...

def latest_requests():
    """returns the history of made requests"""
    ...

def has_request():
    """
    :returns: bool - whether any request has been made
    """
    ...

