"""
This type stub file was generated by pyright.
"""

from urllib.parse import parse_qs, quote, quote_plus, unquote, urlencode, urlsplit, urlunsplit
from http.server import BaseHTTPRequestHandler

unquote_utf8 = unquote
def encode_obj(in_obj):
    ...

class BaseClass(object):
    def __repr__(self):
        ...
    


__all__ = ['BaseClass', 'BaseHTTPRequestHandler', 'quote', 'quote_plus', 'urlencode', 'urlunsplit', 'urlsplit', 'parse_qs']
