"""
This type stub file was generated by pyright.
"""

import logging
import connexion
from flask_testing import TestCase
from doctrans_py_swagger_server.encoder import JSONEncoder

class BaseTestCase(TestCase):
    def create_app(self):
        ...
    


