"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from morpho.types import Options
from typing import List, Optional

class Model(BaseModel):
    class Config:
        extra = ...

class ServiceInfo(Model):
    name: str
    ...

class ListServicesResponse(Model):
    services: List[ServiceInfo]
    ...

class TransformDocumentResponse(Model):
    document: str
    ...

class TransformDocumentRequest(Model):
    document: str
    service_name: str
    ...

class PipeService(Model):
    name: str
    options: Optional[Options]
    ...

class TransformDocumentPipeRequest(Model):
    document: str
    services: List[PipeService]
    ...

class TransformDocumentPipeResponse(Model):
    document: str
    last_transformer: str
    ...

class OptionsPropertyError(Model):
    name: str
    message: str
    ...

class OptionsErrorResponse(Model):
    code: int
    properties: List[OptionsPropertyError]
    ...

class ErrorResponse(Model):
    code: int
    message: str
    ...

if __name__ == "__main__":
    class A(Model):
        a: str
        ...
    a = ErrorResponse()
